// automatically generated by the FlatBuffers compiler, do not modify

/*
** Copyright © 2018, Oracle and/or its affiliates. All rights reserved.
**
** Licensed under the Universal Permissive License v 1.0 as shown at
** http://oss.oracle.com/licenses/upl.
*/
package com.oracle.graphpipefb;

public final class Req {
  private Req() { }
  public static final byte NONE = 0;
  public static final byte InferRequest = 1;
  public static final byte MetadataRequest = 2;

  public static final String[] names = { "NONE", "InferRequest", "MetadataRequest", };

  public static String name(int e) { return names[e]; }
}

