// automatically generated by the FlatBuffers compiler, do not modify

package com.oracle.graphpipefb;

public final class Req {
  private Req() { }
  public static final byte NONE = 0;
  public static final byte InferRequest = 1;
  public static final byte MetadataRequest = 2;

  public static final String[] names = { "NONE", "InferRequest", "MetadataRequest", };

  public static String name(int e) { return names[e]; }
}

